// Generates tokens.css (CSS custom properties) from src/index.ts so web can import the tokens as plain CSS.
// Run with `pnpm --filter @katha/tokens build:css` after editing src/index.ts (Node >= 22.6 strips the types).
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const tokens = await import(pathToFileURL(join(root, "src", "index.ts")).href);
const { colors, radii, spacing, type, fontSize, lineHeight, duration, easing, elevation, zIndex, touchTarget } = tokens;

/** camelCase -> kebab-case, so `lineStrong` becomes `--k-line-strong` rather than a second naming convention. */
const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();

const lines = ["/* Generated by scripts/build-css.mjs from src/index.ts. Do not edit by hand. */", ":root {"];
for (const [k, v] of Object.entries(colors)) lines.push(`  --k-${kebab(k)}: ${v};`);
for (const [k, v] of Object.entries(radii)) lines.push(`  --k-radius-${kebab(k)}: ${v}px;`);
for (const [k, v] of Object.entries(spacing)) lines.push(`  --k-space-${kebab(k)}: ${v}px;`);
for (const [k, v] of Object.entries(type)) lines.push(`  --k-font-${kebab(k)}: "${v}";`);
for (const [k, v] of Object.entries(fontSize)) lines.push(`  --k-text-${kebab(k)}: ${v}px;`);
for (const [k, v] of Object.entries(lineHeight)) lines.push(`  --k-leading-${kebab(k)}: ${v}px;`);
for (const [k, v] of Object.entries(duration)) lines.push(`  --k-duration-${kebab(k)}: ${v}ms;`);
for (const [k, v] of Object.entries(easing)) lines.push(`  --k-ease-${kebab(k)}: ${v};`);
for (const [k, v] of Object.entries(elevation)) lines.push(`  --k-elevation-${kebab(k)}: ${v};`);
for (const [k, v] of Object.entries(zIndex)) lines.push(`  --k-z-${kebab(k)}: ${v};`);
lines.push(`  --k-touch-target: ${touchTarget}px;`);
lines.push("}", "");
writeFileSync(join(root, "tokens.css"), lines.join("\n"));
console.log(`wrote tokens.css (${lines.length - 3} custom properties)`);
