// Generates tokens.css (CSS custom properties) from src/index.ts so web can import the tokens as plain CSS.
// Run with `pnpm --filter @katha/tokens build:css` after editing src/index.ts (Node >= 22.6 strips the types).
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const { colors, radii, spacing, type } = await import(pathToFileURL(join(root, "src", "index.ts")).href);

const lines = ["/* Generated by scripts/build-css.mjs from src/index.ts. Do not edit by hand. */", ":root {"];
for (const [k, v] of Object.entries(colors)) lines.push(`  --k-${k}: ${v};`);
for (const [k, v] of Object.entries(radii)) lines.push(`  --k-radius-${k}: ${v}px;`);
for (const [k, v] of Object.entries(spacing)) lines.push(`  --k-space-${k}: ${v}px;`);
for (const [k, v] of Object.entries(type)) lines.push(`  --k-font-${k}: "${v}";`);
lines.push("}", "");
writeFileSync(join(root, "tokens.css"), lines.join("\n"));
console.log(`wrote tokens.css (${Object.keys(colors).length} colours)`);
