"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-07

Generated by scripts/render_initial_migration.py. Regenerate rather than hand-edit while the schema is young.
"""
from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE TYPE admin_role AS ENUM ('owner', 'editor', 'support', 'finance')")
    op.execute("CREATE TYPE asset_status AS ENUM ('uploaded', 'queued', 'transcoding', 'ready', 'failed')")
    op.execute("CREATE TYPE ledger_kind AS ENUM ('signup_bonus', 'purchase', 'unlock', 'ad_unlock', 'checkin', 'task', 'referral', 'admin_adjust', 'refund')")
    op.execute("CREATE TYPE pack_kind AS ENUM ('coins', 'vip')")
    op.execute("CREATE TYPE platform AS ENUM ('web', 'android', 'ios')")
    op.execute("CREATE TYPE publish_status AS ENUM ('draft', 'review', 'published', 'archived')")
    op.execute("CREATE TYPE purchase_status AS ENUM ('pending', 'paid', 'failed', 'refunded')")
    op.execute("CREATE TYPE report_status AS ENUM ('open', 'resolved', 'dismissed')")
    op.execute("CREATE TYPE reward_frequency AS ENUM ('once', 'daily')")
    op.execute("CREATE TYPE reward_task_kind AS ENUM ('link', 'rewarded_ad', 'share', 'follow')")
    op.execute("CREATE TYPE unlock_method AS ENUM ('coins', 'ad', 'vip', 'free', 'admin')")
    op.execute("CREATE TYPE user_status AS ENUM ('active', 'banned', 'deleted')")
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_placements',
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('slot', sa.String(length=32), nullable=False),
    sa.Column('network', sa.String(length=32), nullable=False),
    sa.Column('unit_id', sa.String(length=160), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'slot', 'network', name='uq_ad_placement')
    )
    op.create_table('admin_users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', postgresql.ENUM('owner', 'editor', 'support', 'finance', name='admin_role', create_type=False), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('analytics_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('platform', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('props', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('variant_map', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_name_ts', 'analytics_events', ['name', 'ts'], unique=False)
    op.create_index('ix_events_user_ts', 'analytics_events', ['user_id', 'ts'], unique=False)
    op.create_table('categories',
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('show_on_home', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('cms_pages',
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('show_in_footer', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('coin_packs',
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', postgresql.ENUM('coins', 'vip', name='pack_kind', create_type=False), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('bonus_coins', sa.Integer(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('google_product_id', sa.String(length=120), nullable=True),
    sa.Column('apple_product_id', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('badge', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('contact_messages',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiments',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('variants', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('allocation', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('feature_flags',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('languages',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('native_name', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_rtl', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('reward_tasks',
    sa.Column('platform', postgresql.ENUM('web', 'android', 'ios', name='platform', create_type=False), nullable=False),
    sa.Column('kind', postgresql.ENUM('link', 'rewarded_ad', 'share', 'follow', name='reward_task_kind', create_type=False), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('timer_seconds', sa.Integer(), nullable=False),
    sa.Column('frequency', postgresql.ENUM('once', 'daily', name='reward_frequency', create_type=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('public_id', sa.String(length=12), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'banned', 'deleted', name='user_status', create_type=False), nullable=False),
    sa.Column('coin_balance', sa.BigInteger(), nullable=False),
    sa.Column('referral_code', sa.String(length=16), nullable=True),
    sa.Column('referred_by_id', sa.UUID(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referred_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('referral_code')
    )
    op.create_table('video_assets',
    sa.Column('source_key', sa.Text(), nullable=False),
    sa.Column('status', postgresql.ENUM('uploaded', 'queued', 'transcoding', 'ready', 'failed', name='asset_status', create_type=False), nullable=False),
    sa.Column('hls_master_key', sa.Text(), nullable=True),
    sa.Column('renditions', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ad_events',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('network', sa.String(length=32), nullable=False),
    sa.Column('ssv_transaction_id', sa.String(length=160), nullable=False),
    sa.Column('ad_unit_id', sa.String(length=160), nullable=True),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('ref_id', sa.String(length=64), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ssv_transaction_id')
    )
    op.create_table('auth_identities',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_uid', sa.String(length=255), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_uid', name='uq_identity_provider_uid')
    )
    op.create_table('cms_page_translations',
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('lang', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['cms_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('page_id', 'lang')
    )
    op.create_table('coin_ledger',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.BigInteger(), nullable=False),
    sa.Column('kind', postgresql.ENUM('signup_bonus', 'purchase', 'unlock', 'ad_unlock', 'checkin', 'task', 'referral', 'admin_adjust', 'refund', name='ledger_kind', create_type=False), nullable=False),
    sa.Column('ref_type', sa.String(length=32), nullable=True),
    sa.Column('ref_id', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('variant_map', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_ledger_user_created', 'coin_ledger', ['user_id', 'created_at'], unique=False)
    op.create_table('experiment_assignments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('experiment_key', sa.String(length=64), nullable=False),
    sa.Column('variant', sa.String(length=32), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_key'], ['experiments.key'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'experiment_key')
    )
    op.create_table('notifications',
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('segment', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offers',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('pack_id', sa.UUID(), nullable=True),
    sa.Column('discount_pct', sa.Integer(), nullable=True),
    sa.Column('eligibility', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['coin_packs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pack_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pack_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['coin_packs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pack_id', 'currency', 'country', name='uq_pack_price')
    )
    op.create_table('purchases',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('pack_id', sa.UUID(), nullable=False),
    sa.Column('gateway', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'paid', 'failed', 'refunded', name='purchase_status', create_type=False), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('coins_granted', sa.Integer(), nullable=False),
    sa.Column('variant_map', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['coin_packs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gateway', 'external_id', name='uq_purchase_gateway_external')
    )
    op.create_table('referrals',
    sa.Column('referrer_id', sa.UUID(), nullable=False),
    sa.Column('referee_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('rewarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['referee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referee_id')
    )
    op.create_table('series',
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.Column('banner_url', sa.Text(), nullable=True),
    sa.Column('trailer_asset_id', sa.UUID(), nullable=True),
    sa.Column('original_language', sa.String(length=10), nullable=False),
    sa.Column('free_episodes', sa.Integer(), nullable=False),
    sa.Column('episode_price', sa.Integer(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('status', postgresql.ENUM('draft', 'review', 'published', 'archived', name='publish_status', create_type=False), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_rating', sa.String(length=8), nullable=True),
    sa.Column('territories', postgresql.ARRAY(String(length=2)), nullable=True),
    sa.Column('window_starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('view_count', sa.BigInteger(), nullable=False),
    sa.Column('like_count', sa.BigInteger(), nullable=False),
    sa.Column('sort_weight', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trailer_asset_id'], ['video_assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('platform', postgresql.ENUM('web', 'android', 'ios', name='platform', create_type=False), nullable=False),
    sa.Column('device_name', sa.String(length=160), nullable=True),
    sa.Column('app_version', sa.String(length=32), nullable=True),
    sa.Column('refresh_token_hash', sa.String(length=128), nullable=False),
    sa.Column('push_token', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    op.create_index('ix_sessions_user_active', 'sessions', ['user_id', 'revoked_at'], unique=False)
    op.create_table('settings',
    sa.Column('namespace', sa.String(length=64), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('namespace')
    )
    op.create_table('ui_translations',
    sa.Column('lang', sa.String(length=10), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lang'], ['languages.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lang', 'key')
    )
    op.create_table('checkins',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('streak_day', sa.Integer(), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('ledger_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ledger_id'], ['coin_ledger.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'day')
    )
    op.create_table('coupon_codes',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('used', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('embeddings',
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('series_id', 'model')
    )
    op.create_index('ix_embeddings_vector', 'embeddings', ['vector'], unique=False, postgresql_using='hnsw', postgresql_ops={'vector': 'vector_cosine_ops'})
    op.create_table('episodes',
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('video_asset_id', sa.UUID(), nullable=True),
    sa.Column('embed_html', sa.Text(), nullable=True),
    sa.Column('price_override', sa.Integer(), nullable=True),
    sa.Column('is_free_override', sa.Boolean(), nullable=True),
    sa.Column('status', postgresql.ENUM('draft', 'review', 'published', 'archived', name='publish_status', create_type=False), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_asset_id'], ['video_assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'number', name='uq_episode_series_number')
    )
    op.create_table('favorites',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'series_id')
    )
    op.create_table('likes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'series_id')
    )
    op.create_table('reward_claims',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('ledger_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ledger_id'], ['coin_ledger.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['reward_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reward_claims_user_task', 'reward_claims', ['user_id', 'task_id', 'created_at'], unique=False)
    op.create_table('series_categories',
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('series_id', 'category_id')
    )
    op.create_table('series_tags',
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('series_id', 'tag_id')
    )
    op.create_table('series_translations',
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('lang', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('seo_title', sa.String(length=70), nullable=True),
    sa.Column('meta_description', sa.String(length=200), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(String(length=64)), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('series_id', 'lang')
    )
    op.create_table('vip_memberships',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('purchase_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vip_user_ends', 'vip_memberships', ['user_id', 'ends_at'], unique=False)
    op.create_table('episode_unlocks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('method', postgresql.ENUM('coins', 'ad', 'vip', 'free', 'admin', name='unlock_method', create_type=False), nullable=False),
    sa.Column('ledger_id', sa.UUID(), nullable=True),
    sa.Column('variant_map', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ledger_id'], ['coin_ledger.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'episode_id', name='uq_unlock_user_episode')
    )
    op.create_table('reports',
    sa.Column('reporter_id', sa.UUID(), nullable=True),
    sa.Column('series_id', sa.UUID(), nullable=True),
    sa.Column('episode_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('open', 'resolved', 'dismissed', name='report_status', create_type=False), nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subtitles',
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('lang', sa.String(length=10), nullable=False),
    sa.Column('vtt_key', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('episode_id', 'lang', name='uq_subtitle_episode_lang')
    )
    op.create_table('watch_progress',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('position_sec', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'episode_id')
    )
    op.create_index('ix_watch_user_updated', 'watch_progress', ['user_id', 'updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_watch_user_updated', table_name='watch_progress')
    op.drop_table('watch_progress')
    op.drop_table('subtitles')
    op.drop_table('reports')
    op.drop_table('episode_unlocks')
    op.drop_index('ix_vip_user_ends', table_name='vip_memberships')
    op.drop_table('vip_memberships')
    op.drop_table('series_translations')
    op.drop_table('series_tags')
    op.drop_table('series_categories')
    op.drop_index('ix_reward_claims_user_task', table_name='reward_claims')
    op.drop_table('reward_claims')
    op.drop_table('likes')
    op.drop_table('favorites')
    op.drop_table('episodes')
    op.drop_index('ix_embeddings_vector', table_name='embeddings', postgresql_using='hnsw', postgresql_ops={'vector': 'vector_cosine_ops'})
    op.drop_table('embeddings')
    op.drop_table('coupon_codes')
    op.drop_table('checkins')
    op.drop_table('ui_translations')
    op.drop_table('settings')
    op.drop_index('ix_sessions_user_active', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('series')
    op.drop_table('referrals')
    op.drop_table('purchases')
    op.drop_table('pack_prices')
    op.drop_table('offers')
    op.drop_table('notifications')
    op.drop_table('experiment_assignments')
    op.drop_index('ix_ledger_user_created', table_name='coin_ledger')
    op.drop_table('coin_ledger')
    op.drop_table('cms_page_translations')
    op.drop_table('auth_identities')
    op.drop_table('ad_events')
    op.drop_table('video_assets')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('reward_tasks')
    op.drop_table('languages')
    op.drop_table('feature_flags')
    op.drop_table('experiments')
    op.drop_table('contact_messages')
    op.drop_table('coin_packs')
    op.drop_table('cms_pages')
    op.drop_table('categories')
    op.drop_index('ix_events_user_ts', table_name='analytics_events')
    op.drop_index('ix_events_name_ts', table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_table('admin_users')
    op.drop_table('ad_placements')
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS admin_role")
    op.execute("DROP TYPE IF EXISTS asset_status")
    op.execute("DROP TYPE IF EXISTS ledger_kind")
    op.execute("DROP TYPE IF EXISTS pack_kind")
    op.execute("DROP TYPE IF EXISTS platform")
    op.execute("DROP TYPE IF EXISTS publish_status")
    op.execute("DROP TYPE IF EXISTS purchase_status")
    op.execute("DROP TYPE IF EXISTS report_status")
    op.execute("DROP TYPE IF EXISTS reward_frequency")
    op.execute("DROP TYPE IF EXISTS reward_task_kind")
    op.execute("DROP TYPE IF EXISTS unlock_method")
    op.execute("DROP TYPE IF EXISTS user_status")
