"""Render the initial Alembic migration from the models without a live Postgres.

Alembic's autogenerate compares metadata against a database. We point it at an empty in-memory
SQLite connection so the diff is "create everything", while the rendered types stay the
Postgres-specific ones declared on the models (JSONB, UUID, ARRAY, Vector, enums).

Enum types are created explicitly up front and every column uses create_type=False, because
several enums (platform, publish_status) are shared by more than one table and Postgres would
otherwise see a duplicate CREATE TYPE.
"""

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import sqlalchemy as sa  # noqa: E402
from alembic.autogenerate import produce_migrations, render_python_code  # noqa: E402
from alembic.migration import MigrationContext  # noqa: E402
from sqlalchemy import create_engine  # noqa: E402

from app.core.db import Base  # noqa: E402
from app.models import *  # noqa: F401,F403,E402

engine = create_engine("sqlite://")
with engine.connect() as conn:
    ctx = MigrationContext.configure(conn, opts={"compare_type": True})
    script = produce_migrations(ctx, Base.metadata)

upgrade = render_python_code(script.upgrade_ops, alembic_module_prefix="op.", sqlalchemy_module_prefix="sa.")
downgrade = render_python_code(script.downgrade_ops, alembic_module_prefix="op.", sqlalchemy_module_prefix="sa.")

# Every enum column becomes postgresql.ENUM(..., create_type=False); types are created below.
upgrade = re.sub(r"sa\.Enum\(([^)]*)\)", r"postgresql.ENUM(\1, create_type=False)", upgrade)

enums: dict[str, list[str]] = {}
for table in Base.metadata.sorted_tables:
    for col in table.columns:
        if isinstance(col.type, sa.Enum) and col.type.name:
            enums.setdefault(col.type.name, list(col.type.enums))

create_types = "\n".join(
    f'    op.execute("CREATE TYPE {name} AS ENUM ({", ".join(repr(v) for v in values)})")'
    for name, values in sorted(enums.items())
)
drop_types = "\n".join(f'    op.execute("DROP TYPE IF EXISTS {name}")' for name in sorted(enums))

template = '''"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-07

Generated by scripts/render_initial_migration.py. Regenerate rather than hand-edit while the schema is young.
"""
from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
{create_types}
{upgrade}


def downgrade() -> None:
{downgrade}
{drop_types}
'''

out = Path(sys.argv[1] if len(sys.argv) > 1 else "alembic/versions/0001_initial.py")
out.write_text(
    template.format(create_types=create_types, upgrade=upgrade, downgrade=downgrade, drop_types=drop_types),
    encoding="utf-8",
)
print(f"wrote {out}: {len(enums)} enum types, {upgrade.count('op.create_table')} tables")
